### ISSUE TITLE
How to retrieve device list from gpoddersync

### ISSUE THREAD

**Issue by lhassell** [thrillfall/nextcloud-gpodder#123]
I need to find the name of the devices that are linked to my gpoddersync instance. I have so far been unable to find that info. Can someone let me know if this is possible?

**Comment by JonOfUs** [comment]
Since this app uses Nextcloud's authentication, the devices will be in the list under 'Nextcloud/settings/security'. There, all devices that logged into your Nextcloud account are listed together with their last authentication timestamp. Be aware that not all of the listed entries there will be connected to gpoddersync since other authenticated apps (like the Nextcloud Android app) also have their own eitries per device.
