### ISSUE TITLE
Newbie needs helps to start syncing

### ISSUE THREAD

**Issue by lmjst** [thrillfall/nextcloud-gpodder#165]
Hi,
Can someone just tells me how to sync podcasts feeds once nextcloud-gpodder has been activated on a nextcloud instance ?
I can't see how to switch from gpodder.net to my nextcloud URL.
In gpodder locally I've changed the gpodder.net server / username / password field values to my nextcloud values but noting happens (not that I imagine this is magic !).
The error message is :
```
error while uploading 
Could not find your device.
Check login is a username (not an email)
and that the device name matches one in your account
```
Where do I check the device name in which account ?

Thanks
dd

details :
 GPodder Sync
Thrillfall Sous licence AGPL
3.8.3

on nextcloud 28.0.4

**Comment by JonOfUs** [comment]
Hi, sadly this app currently doesn't support the official gPodder podcast client as the API has different endpoints due to the Nextcloud URL schema.
You could take a look at projects like https://github.com/bohwaz/micro-gpodder-server for hosting a small syncing service that supports the gPodder client (I never tested the software, so I don't know how stable it currently is).

**Comment by lmjst** [comment]
Yes yes yes! Thanks a lot for the tip.
https://github.com/bohwaz/micro-gpodder-server is exactly what I was looking for and it works!
dd

PS maybe a name like "nextcloud-gpodder-style" for your app might be more straightforward since it doesn't sync gpodder.
