### ISSUE TITLE
Time zone of timestamps

### ISSUE THREAD

**Issue by ByteHamster** [thrillfall/nextcloud-gpodder#184]
Hi,

when looking into https://github.com/AntennaPod/AntennaPod/issues/7453, I noticed that this nextcloud plugin does not seem to support specifying a time zone for the timestamps: https://github.com/thrillfall/nextcloud-gpodder/blob/a7729b29b0c46082d61271f0cdfd24ee5587037c/lib/Core/EpisodeAction/EpisodeActionSaver.php#L19

To work around issues with server time zones, I am considering to explicitly send the time zone in AntennaPod's requests. The [gpodder documentation](https://gpoddernet.readthedocs.io/en/latest/api/reference/events.html) just states that the time zone should be ISO 8601. While their examples do not specify the time zone, the ISO 8601 does cover time zones as well.

I unfortunately don't have a nextcloud server to test currently, so I am asking here. Would sending time zones break parsing in this nextcloud plugin?

**Comment by JonOfUs** [comment]
Hi,

sorry for the late reply.

It seems like this app currently does not support timezones and we expect all timestamps to be in UTC.
I think this should be changed on our side, the app currently crashes if e.g. `2024-11-27T00:00:00+01:00` comes in. However, since we cannot make sure that all Nextcloud servers would receive such an update in the near future, would it be problematic if AntennaPod just continues to send timestamps in UTC?

**Comment by ByteHamster** [comment]
The problem is that people blame AntennaPod for any problems caused by the web server using different time zones. There are currently implementations of  podcast servers, so there is no way we can make sure that they all use UTC. So we should really send the time zone to make sure that the time stamps are correct.

For Nextcloud, I suggest to implement the feature on the server. Then we wait a few months until everyone had the chance to upgrade. Then we release the time zones in AntennaPod.
