### ISSUE TITLE
Other clients than AntennaPod

### ISSUE THREAD

**Issue by teemue** [thrillfall/nextcloud-gpodder#51]
Thanks for this syncing app! 

Is it possible to sync other clients as well? I tried the official gpodder app but it could not connect to my instance.

**Comment by JonOfUs** [comment]
No, this isn't possible yet. Those clients would have to add this feature themselves.
This is due to some sync features missing in gopddersync, different API urls and the Nextcloud-specific authentication method.

But adding such a sync with gpoddersync would be rather easy since all the api requests and responses are the same or compatible (except the url), it would only be necessary to implement an authentication to Nextcloud - but there are good libraries and example code snippets for this.

**Comment by m4lvin** [comment]
The KDE application **Kasts** also supports nextcloud-gpoddersync since version 21.12: https://apps.kde.org/kasts/

**Comment by JonOfUs** [comment]
I didn't know that Kasts already has a working integration, this sounds great!

Yeah. the developer of the podcast app has already expressed his interest in the AntennaPod PR: https://github.com/AntennaPod/AntennaPod/pull/5243/#issuecomment-870419935
