### ISSUE TITLE
Error on sync

### ISSUE THREAD

**Issue by mrsadowski** [thrillfall/nextcloud-gpodder#58]
I've installed new (2.5.0) version of AntennaPod and nextcloud-gpodder (Nextcloud version 20.0.14). I was able to sign in and authorize app, but whenever I try to sync, I get "attempt to invoke virtual method 'java.lang.String okhttp3.HttpUrl.host()' on a null object reference". Don't know how to debug further.

**Comment by EwenKorr** [comment]
The issue already exists on the AntennaPod side: https://github.com/AntennaPod/AntennaPod/issues/5805

**Comment by JonOfUs** [comment]
The issue will be fixed with v2.5.1, so one can just wait for the update.

In the meantime, a workaround for me was to remove all local folder subscriptions, then enable Synchronization and then re-add all local folder subscriptions. Keep in mind that probably all the listen timestamps will be gone, but this works since the problem was that local folder subscriptions got synchronized during full syncs and their URLs threw errors in AntennaPod.
