### ISSUE TITLE
Error 302 when trying to upload subscriptions from gPodder app on Kubuntu

### ISSUE THREAD

**Issue by joho500** [thrillfall/nextcloud-gpodder#60]
Hi,

I have subscriptions in my gPodder app and tried to upload them to my newly installed gpodder-sync on my Nextcloud server but it reported '`Error during upload. 302'`.

Info on my setup:
I have my nextcloud server running behind the firewall of my router with a port forward from 4433 external to 433 internal. I have 2FA enabled in nextcloud and created an app password for gPodder. I think it connects OK because when looking for new podcasts I can populate the 'gpodder.net - Top 50' list.

Hope you can help.

**Comment by JonOfUs** [comment]
The problem is that the gPodder app does not support synchronization with Nextcloud (currently). You can find podcast clients that support syncing in the [Readme](https://github.com/thrillfall/nextcloud-gpodder).

So until support for gpoddersync (this Nextcloud app) gets implemented into gPodder, synchronization sadly won't work.
We can't support it in this app, because Nextcloud limits how api URLs can be structured and this way, gpoddersync will always have different api urls than gpodder.net.

**Comment by joho500** [comment]
OK. That's too bad. I will try one of the supported apps.
Thanks.
