### ISSUE TITLE
parameter 'since' doesn't appear to be optional

### ISSUE THREAD

**Issue by HassoSigbjoernson** [thrillfall/nextcloud-gpodder#72]
According the documentation 'since' is optional but that doesn't appear to be the case.

`curl --user "user:password" https://domain/apps/gpoddersync/episode_action` returns the following error while the same command with an appended `?since=0` works just fine. Haven't tested the other API endpoints.

`Exception: OCA\GPodderSync\Controller\EpisodeActionController::list(): Argument #1 ($since) must be of type int, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/html/custom_apps/gpoddersync/lib/Controller/EpisodeActionController.php' line 56`

**Comment by JonOfUs** [comment]
Yes, you're right. It seems that the parameter is only optional for subscription changes.

@thrillfall should the default value for `$since` be 0 instead of `-1 week`? (for subscription changes as well as episode actions) The gpodder.net API seems to handle it this way: https://gpoddernet.readthedocs.io/en/latest/api/reference/events.html#get-episode-actions

**Comment by JonOfUs** [comment]
> I thought the default should be some time span. What is the purpose of 0 as default? The result is always empty then

No, it represents a unix timestamp and so it would respond with all EpisodeChanges/SubscriptionChanges on the server (all since 1970).

**Comment by thrillfall** [comment]
> > I thought the default should be some time span. What is the purpose of 0 as default? The result is always empty then
> 
> No, it represents a unix timestamp and so it would respond with all EpisodeChanges/SubscriptionChanges on the server (all since 1970).

Well in that case a default 0 would be good.
