### ISSUE TITLE
Syncing kasts results in all episodes being marked as played 

### ISSUE THREAD

**Issue by Uatschitchun** [thrillfall/nextcloud-gpodder#76]
I'm syncing AntennaPod nicely.
I tried kasts and entered my credentials. After initial sync, all episoded are marked as played, so play stated do not get synced correctly!?

https://bugs.kde.org/show_bug.cgi?id=454553

**Comment by JonOfUs** [comment]
I don't know how Kasts handles marking episodes as played. I just tested it and it seems like Kasts marks all episodes as played that were published before the podcast got subscribed. If I subscribe to a random podcast, all episodes are instantly marked/displayed as played.
Does this happen on your device as well?

If so, the error probably is a feature of Kasts and so we cannot do something about it over here. To resolve this issue, maybe an option to disable this feature in Kasts would be good.

![kasts](https://user-images.githubusercontent.com/11487762/170871577-0ace93cc-0857-486f-8c76-66406fe62a00.png)
Just subscribed to this show using kasts, all episodes are marked as played. Then started listening to one episode.

![antennapod](https://user-images.githubusercontent.com/11487762/170871587-a9c90ba8-fce5-4b3d-99dc-b42076c7aa65.png)
Synced with Antennapod, there no episode is marked as played. Listening timestamp is correctly synced.

**Comment by mogwa1** [comment]
(Kasts developer here)

The submitter also opened a similar bug report for kasts: https://bugs.kde.org/show_bug.cgi?id=454553

Kasts does indeed mark all episodes on new feeds as played when importing them.  However, the inital "mark as played" statuses will never be synced; they're only for internal bookkeeping to not overwhelm the user with hundreds of new episodes in the queue.  Actually, Antennapod does the same thing: it marks all episodes (except the latest) of a new feed as played.  It also doesn't sync this state to other devices.

Anyway, to come back to the issue: I suspect that it's based on a misunderstanding of what syncing in Antennapod and Kasts does.  Both apps will only sync episodes states that have *changed* after the sync has been set up.  None of the pre-existing play positions will be synced.  In fact, that would be a disaster waiting to happen because there would be no way to correctly resolve conflicts without having the state-change timestamps.

**Comment by Uatschitchun** [comment]
@mogwa1 Yes, I opened the issue here and also on bugs.kde.org as I did not know which one is the correct to address.

**Comment by Uatschitchun** [comment]
@mogwa1 At https://bugs.kde.org/show_bug.cgi?id=454553 you state:
> PS: If I recall correctly, you can force AntennaPod to upload all *existing* episode states to the server, but I'm not entirely sure. 
Is that true for AntennaPod?

**Comment by JonOfUs** [comment]
> Kasts does indeed mark all episodes on new feeds as played when importing them

Thanks for clarifying :)

> Actually, Antennapod does the same thing: it marks all episodes (except the latest) of a new feed as played. 

I never witnessed this in Antennapod, is this maybe Opt-In? In the screenshot above old episodes were not marked as played in AntennaPod after adding the feed.

Since this repository has nothing to do with the issues/misunderstandings, we should probably close this issue and discuss this elsewhere - since this sounds like a question regarding Kasts' synchronization behaviour, probably in the mentioned issue on bugs.kde.org?

**Comment by mogwa1** [comment]
> > Actually, Antennapod does the same thing: it marks all episodes (except the latest) of a new feed as played.
> 
> I never witnessed this in Antennapod, is this maybe Opt-In? In the screenshot above old episodes were not marked as played in AntennaPod after adding the feed.
Mmm, looks like you're right.  I must have misremembered this.  Sorry for that.
> Since this repository has nothing to do with the issues/misunderstandings, we should probably close this issue and discuss this elsewhere - since this sounds like a question regarding Kasts' synchronization behaviour, probably in the mentioned issue on bugs.kde.org?
I agree.  Let's close it here.
Just for reference for anyone who might still look at this issue in the future: this gpodder-sync API does not have "played" attribute.  It will just sync the current play position.  This means that apps have to guess the "played" state anyway for episodes that have never been touched.  In its current state, it will never be able to reliably sync the "played" state between apps.  I've tried my best to implement something that makes sense for the "played" state in Kasts for episodes that *have* been touched since the sync was set up.
