### ISSUE TITLE
Does not appear in the nextcloud store

### ISSUE THREAD

**Issue by Schoebi** [thrillfall/nextcloud-gpodder#87]
I'm running a yunohost.org machine, but this app does not appear in the nextcloud store.

Anyone an idea about it?

**Comment by JonOfUs** [comment]
Hi,
this app needs at least php 7.4 and Nextcloud 20.
Yunohost currently seems to use Nextcloud 22, so your problem probably is that your instance still uses php 7.3. You can check your php version under Settings -> System (if you are an admin of your instance).
If it's still 7.3, you'll have to upgrade php in order to install this app, how this is done (if it's possible) can probably be found somewhere in the Yunohost docs.
