### ISSUE TITLE
full remove

### ISSUE THREAD

**Issue by fabrikant** [thrillfall/nextcloud-gpodder#94]
How can I completely uninstall an app? After a normal uninstall, tables remain in the database.

**Comment by thrillfall** [comment]
Erm, i never thought about that. Lets add this to the todo list

**Comment by JonOfUs** [comment]
There is no good way to do this in Nextcloud, a feature request in Nextcloud Server is still open: https://github.com/nextcloud/server/issues/5539 (other apps don't allow this either)

Deleting the tables could lead to problems since they wouldn't be restored when the app gets reinstalled (since the migrations are already executed). But a way to drastically minimize the database usage if wanted would be the "reset" functionality mentioned here: https://github.com/thrillfall/nextcloud-gpodder/issues/81#issuecomment-1179773852. This way, one could remove all podcast data so that only the table schemes stay in the database which occupy nearly no storage.

**Comment by fabrikant** [comment]
I got it. It's required these SQL requests.
```
use nextcloud;
drop table oc_gpodder_episode_action;
drop table oc_gpodder_subscriptions;
delete from oc_appconfig where appid="gpoddersync";
delete from oc_migrations where app="gpoddersync";
```
